name: 'Deploy'

on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'

env:
  IMAGE_NAME: "ghcr.io/flipperdevices/lab.flipper.net"

jobs:
  build:
    runs-on: [FlipperZeroShell]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Set image tag'
        id: tag
        run: |
          IMAGE_TAG="0.0.0"
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=${{ github.ref }};
            TAG_FULL=${REF#refs/*/};
            IMAGE_TAG=${TAG_FULL//\//_};
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: 'Build docker image'
        run: |
          docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: 'Upload docker image'
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"

      - name: 'Show image digest'
        run: |
          docker image inspect --format='{{index .RepoDigests 0}}' "$IMAGE_NAME:$IMAGE_TAG" | awk -F '@' '{print $2}'

      - name: 'Trigger k8s to use new image'
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ${{ secrets.INFRASTRUCTURE_REPO }}
          token: ${{ secrets.K8S_GITHUB_PAT }}
          event-type: lab-flipper-net-deploy
          client-payload: '{"image_tag": "${{steps.tag.outputs.image_tag}}"}'
